luajit: ...hishb/maverick/torch_cuda/share/lua/5.1/nn/Container.lua:67: 
In 1 module of nn.Sequential:
...ashishb/maverick/torch_cuda/share/lua/5.1/cudnn/init.lua:64: assertion failed!
stack traceback:
	[C]: in function 'assert'
	...ashishb/maverick/torch_cuda/share/lua/5.1/cudnn/init.lua:64: in function 'toDescriptor'
	...ck/torch_cuda/share/lua/5.1/cudnn/SpatialConvolution.lua:116: in function 'createIODescriptors'
	...ck/torch_cuda/share/lua/5.1/cudnn/SpatialConvolution.lua:360: in function <...ck/torch_cuda/share/lua/5.1/cudnn/SpatialConvolution.lua:357>
	[C]: in function 'xpcall'
	...hishb/maverick/torch_cuda/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	...ishb/maverick/torch_cuda/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	...hb/maverick/torch_cuda/share/lua/5.1/nngraph/gmodule.lua:311: in function 'neteval'
	...hb/maverick/torch_cuda/share/lua/5.1/nngraph/gmodule.lua:346: in function 'forward'
	dummy.lua:29: in main chunk
	[C]: at 0x004051e0

WARNING: If you see a stack trace below, it doesn't point to the place where this error occured. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	...hishb/maverick/torch_cuda/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	...ishb/maverick/torch_cuda/share/lua/5.1/nn/Sequential.lua:44: in function 'func'
	...hb/maverick/torch_cuda/share/lua/5.1/nngraph/gmodule.lua:311: in function 'neteval'
	...hb/maverick/torch_cuda/share/lua/5.1/nngraph/gmodule.lua:346: in function 'forward'
	dummy.lua:29: in main chunk
	[C]: at 0x004051e0
